[package]
name = "jieplag"
version = "0.1.0"
authors = ["Jiajie Chen <c@jia.je>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkr-gst = "0.1.1"
clang = "1.0.2"
structopt = "0.3.21"
regex = "1.4.2"
walkdir = "2.3.1"
anyhow = "1.0.35"
log = "0.4.11"
env_logger = "0.8.2"
